"""Generate benchmark/leaderboard.md from the measured reports.

    python scripts/build_leaderboard.py

WHY THIS IS GENERATED NOW

The leaderboard was hand maintained markdown. An audit found it carrying figures
from a corpus that no longer existed, and nothing could have caught that,
because nothing read it.

A leaderboard whose numbers are typed is a leaderboard that will be wrong. This
reads `eval/report.json` for SUTRA's row and the baselines, so a run that
changes the result changes the table. The rows that come from `score.py` on the
benchmark corpus are still transcribed, and each says so.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVAL = ROOT / "eval" / "report.json"
CANONICAL = ROOT / "eval" / "canonical.json"
CORPUS = ROOT / "data" / "corpus"
TARGET = ROOT / "benchmark" / "leaderboard.md"


def read(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def f_beta(precision: float, recall: float, beta: float = 0.5) -> float:
    if precision + recall == 0:
        return 0.0
    b2 = beta * beta
    return (1 + b2) * precision * recall / (b2 * precision + recall)


def main() -> int:
    if not EVAL.exists():
        raise SystemExit("eval/report.json missing, run: make eval")
    ev = read(EVAL)
    canonical = read(CANONICAL)
    head = canonical["headline"]

    manifest = read(CORPUS / "manifest.json")
    cases = ev["corpus"]["cases"]
    rows_n = ev["corpus"]["accused_rows"]
    people = ev["corpus"]["true_persons"]
    true_pairs = ev["blocking"].get("candidate_pairs")

    entries = [(
        "SUTRA, Layers 1 to 7",
        "engine derived, cost weighted",
        head["precision"], head["recall"], head["f1"],
        head["f_beta_0_5"],
        ev["headline"].get("false_positive_pairs"),
    )]
    for name, m in sorted(ev["baselines"].items(), key=lambda kv: -kv[1]["f1"]):
        entries.append((
            name.title() if name.islower() else name,
            "exact key equality",
            m["precision"], m["recall"], m["f1"],
            f_beta(m["precision"], m["recall"]),
            m.get("false_positive_pairs"),
        ))

    corpus_label = f"{manifest['counts'].get('name_pool', 86)} form fixture, {cases:,} cases"
    rows = "\n".join(
        f"| {i} | {name} | {corpus_label} | {cut} | {p:.4f} | {r:.4f} "
        f"| {f1:.4f} | **{fb:.4f}** | {fp:,} | task authors |"
        for i, (name, cut, p, r, f1, fb, fp) in enumerate(entries, start=1)
    )

    deployable = canonical["products"].get("deployable")
    ceiling = canonical["ceiling_argument"]

    text = f"""<!-- Generated by scripts/build_leaderboard.py from eval/report.json.
     Do not edit by hand. It was hand maintained once and went stale. -->

# IERB-P leaderboard

Task version 1.0, default configuration. {cases:,} cases, seed {manifest['seed']},
{rows_n:,} accused rows, {people:,} gold people.

Ranked by **F beta 0.5**, which weights precision twice as heavily as recall.
See `README.md` for why that is the primary metric rather than F1.

Every row states the corpus it ran on and the cut it used, because a figure
without those two is not comparable to anything.

| # | Method | Corpus | Cut | Precision | Recall | F1 | **F0.5** | Wrong merges | Submitted by |
|---|---|---|---|---|---|---|---|---|---|
{rows}

Row 1 is the canonical SUTRA headline, `eval/canonical.json`. The cut is derived
from the fitted prior and the false merge cost ratio, with no label involved.
See ADR 028.

All rows were produced by the task authors, which is a weakness of the current
table and not a strength. A leaderboard whose entries all come from one team is
an internal evaluation with extra formatting. It becomes a benchmark when
someone else appears on it.

## Reproducing every row

```
./generate.sh
python baseline.py --corpus corpus --out baseline_output.csv
python score.py baseline_output.csv
```

Every figure above is read from `eval/report.json` by
`scripts/build_leaderboard.py`. Nothing in this file is typed by hand.

## Reading the table

**Recall alone is not a result.** A method can reach high recall by collapsing
the corpus into one cluster, and the metric that notices is precision. Compare
the F0.5 column rather than the recall column.

**The gap between row 1 and the best baseline is the whole task.** Everything
between a crude folded key and a calibrated probabilistic model is what a
submission can work in.

## Known ceilings

A reference blocking scheme proposes {ev['blocking']['pairs_completeness_pct']:.2f}% of true pairs, so recall
above that means a method is not blocking or has a bug.

Fitting the same probabilistic model from ground truth, the oracle, reaches F1
**{ceiling['oracle_f1']:.4f}**. That bounds this model family, Fellegi Sunter over
discretised agreement levels with conditional independence assumed. It does not
bound a different family, and whether one could do better on these columns is
not measured here.

## A second operating point

{'| | Precision | Recall | F1 | F0.5 |' if deployable else ''}
{'|---|---|---|---|---|' if deployable else ''}
{f"| Deployable, precision at or above 0.95 | **{deployable['precision']:.4f}** | {deployable['recall']:.4f} | {deployable['f1']:.4f} | {deployable['f_beta_0_5']:.4f} |" if deployable else 'Not measured.'}

Submissions may report at either cut and must say which.
"""
    TARGET.write_text(text, encoding="utf-8")
    print(f"leaderboard written, {len(entries)} rows")
    print(f"  SUTRA F0.5 {head['f_beta_0_5']:.4f}, F1 {head['f1']:.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
