"""Vendor the four SUTRA typefaces as local woff2.

The Catalyst deployment runs under a strict CSP with no external hosts, so a
Google Fonts link tag works in development and fails silently on deploy,
leaving a government portal rendered in Times New Roman. The fonts have to be
served from our own origin.

This script is the reproducible record of where they came from. It is run once
and its output is committed. It is not part of the build, and the app never
reaches the network at runtime.

    python scripts/vendor_fonts.py

Writes web/public/fonts/*.woff2 and web/src/styles/fonts.css.

Only the subsets SUTRA actually renders are kept. Latin and latin extended for
the three Latin faces, Kannada and Latin for Noto Sans Kannada. Cyrillic, Greek
and Vietnamese are dropped, which is most of the payload.

Licences. All four are SIL Open Font License 1.1, which permits redistribution
including bundling with an application. The licence text belongs alongside the
files in any release, see web/public/fonts/OFL.txt.
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "web" / "public" / "fonts"
CSS_OUT = ROOT / "web" / "src" / "styles" / "fonts.css"

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0 Safari/537.36")

# (family label, css2 query, subsets to keep, local file stem)
FAMILIES = [
    ("Bricolage Grotesque",
     "Bricolage+Grotesque:opsz,wght@12..96,400..700",
     {"latin", "latin-ext"}, "bricolage-grotesque"),
    ("Inter Tight",
     "Inter+Tight:wght@400..600",
     {"latin", "latin-ext"}, "inter-tight"),
    ("JetBrains Mono",
     "JetBrains+Mono:wght@400..700",
     {"latin", "latin-ext"}, "jetbrains-mono"),
    ("Noto Sans Kannada",
     "Noto+Sans+Kannada:wght@400..600",
     {"kannada", "latin"}, "noto-sans-kannada"),
]

BLOCK_RE = re.compile(
    r"/\*\s*(?P<subset>[a-z0-9-]+)\s*\*/\s*@font-face\s*\{(?P<body>[^}]*)\}",
    re.IGNORECASE,
)
URL_RE = re.compile(r"url\((?P<url>https://[^)]+\.woff2)\)")
RANGE_RE = re.compile(r"unicode-range:\s*(?P<range>[^;]+);")
WEIGHT_RE = re.compile(r"font-weight:\s*(?P<weight>[^;]+);")


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=45) as response:
        return response.read()


def main() -> int:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    faces: list[str] = []
    total_bytes = 0

    for label, query, subsets, stem in FAMILIES:
        css_url = f"https://fonts.googleapis.com/css2?family={query}&display=swap"
        print(f"{label}")
        try:
            css = fetch(css_url).decode("utf-8")
        except Exception as exc:  # noqa: BLE001
            print(f"  FAILED to fetch css, {exc}", file=sys.stderr)
            return 1

        kept = 0
        for match in BLOCK_RE.finditer(css):
            subset = match.group("subset").lower()
            if subset not in subsets:
                continue
            body = match.group("body")
            url_match = URL_RE.search(body)
            range_match = RANGE_RE.search(body)
            weight_match = WEIGHT_RE.search(body)
            if not url_match:
                continue

            filename = f"{stem}-{subset}.woff2"
            target = FONT_DIR / filename
            try:
                data = fetch(url_match.group("url"))
            except Exception as exc:  # noqa: BLE001
                print(f"  FAILED {filename}, {exc}", file=sys.stderr)
                return 1
            target.write_bytes(data)
            total_bytes += len(data)
            kept += 1
            print(f"  {filename:<38} {len(data) / 1024:>7.1f} KB  {subset}")

            weight = weight_match.group("weight").strip() if weight_match else "400"
            unicode_range = range_match.group("range").strip() if range_match else None
            face = [
                "@font-face {",
                f"  font-family: '{label}';",
                "  font-style: normal;",
                f"  font-weight: {weight};",
                # swap, because a government portal must render its text
                # immediately rather than block on a font that may not arrive.
                "  font-display: swap;",
                f"  src: url('/fonts/{filename}') format('woff2');",
            ]
            if unicode_range:
                face.append(f"  unicode-range: {unicode_range};")
            face.append("}")
            faces.append("\n".join(face))

        if kept == 0:
            print(f"  FAILED, no matching subsets for {label}", file=sys.stderr)
            return 1

    header = [
        "/*",
        " * Vendored typefaces. Generated by scripts/vendor_fonts.py, do not edit.",
        " *",
        " * Served from our own origin because the Catalyst deployment runs under a",
        " * strict CSP with no external hosts. A Google Fonts link tag works in",
        " * development and fails on deploy.",
        " *",
        " * All four are SIL Open Font License 1.1. See public/fonts/OFL.txt.",
        " *",
        f" * {len(faces)} faces, {total_bytes / 1024:.0f} KB total.",
        " */",
        "",
    ]
    CSS_OUT.write_text("\n".join(header) + "\n\n".join(faces) + "\n", encoding="utf-8")

    print()
    print(f"{len(faces)} faces, {total_bytes / 1024:.0f} KB")
    print(f"wrote {CSS_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
